# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - pip install numpy
  - pip install git+https://github.com/rabix/sbpack
